### ISSUE TITLE
Paste plugins?

### ISSUE THREAD

**Issue by ryantheleach** [jkcclemens/paste#107]
**Is your feature request related to a problem? Please describe.**
In the Minecraft community, people have created browser extensions for remapping stack traces / code. It would be cool if paste could have any sort of processing functionality for obfuscation mappings.

**Describe the solution you'd like**
Clearly Paste's scope is wider then the Minecraft community, and the main reason that people fork / create their own services in the first place is to have more control over paste service functionality. Would you be open to having a plugin/extension system allowing for extensions to paste?

**Describe alternatives you've considered**
Forking and maintaining a paste fork, browser extenstions

**Comment by jkcclemens** [comment]
I'm still not sure what I think about this. The idea is modules that can be dynamically loaded by a server operator.

I'm not sure what sort of API that would include and I'm not sure how complex that would make our underlying code, which is not pretty right now.

I feel favourable about making extensions for these kind of specific issues, but I understand that is fraught with annoyances like minor adjustments to layouts becoming breaking changes. However, it is much less work for me, and keeps the codebase simple without introducing potential for new bugs/attack vectors. On the other hand, it wouldn't affect the API and asks users to install something. On the other other hand, it's a very niche use-case that I can't really see the justification for having an entire subsystem to add and maintain, and those users could probably handle installing an extension.

Any sort of plugin would have to be a `.so` or `.dylib` that would have to be compiled (albeit, from any language that can compile to a shared library) and match the ABI for paste's "plugin API." I see high potential for crashes when interacting with Rust from non-Rust due to memory management, and if the ABI changes without an upgrade for the plugin, the server will crash, which will lead to more support and a more unstable product.

I'm leaning towards a no for this. @AKPWebDesign mentioned allowing instance operators to add their own JS instead of doing a more backend solution, and I'd like to point out that you can currently do this by editing templates. Obviously, this also doesn't affect the API and won't work for users with JS off, but it doesn't require an installation of an extension.

**Comment by ryantheleach** [comment]
Honestly with the way the web is going these days, being able to edit the template is probably good enough anyway (and this was more an off the top of my head request, wondering what you were thinking long term, as I'm not even yet a user). Additional functionality could be provided by another micro-service as long as rest API's / auth exists for paste.

**Comment by jkcclemens** [comment]
paste does have a REST API with and without authentication, so another service could interact with paste to clean up stack traces, yes. An extension could even tap into that and query the API based on the paste ID in the URL, since that's all that's necessary (except for private pastes, in which case, scraping or asking for an API key are options).

I'm going to close this, since I'm not going to be implementing it, but feel free to ask questions on Discord or open other issues for other ideas! :)
