### ISSUE TITLE
Contributing is too hard

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#167]
Getting a working development instance of paste up and running to test changes is difficult. I forget how to do it, and I made the damn thing.

I would like to simplify the process so that new (and old) contributors can more easily test changes and get them merged!

# Current development instance setup

This uses Docker, since it's really the only reasonable way to run paste.

1. Generate a self-signed certificate for some local domain for paste.
2. Set browsers to trust certificate.
3. Edit hosts file to point the fake domain to `localhost`.
4. Clone the repository (and make sure to clone submodules)
5. Copy several config files and edit them, often with settings that Docker requires.
6. Make sure config files point to self-signed cert.
7. `docker-compose -f .docker/docker-compose.development.yml up -d`
    - This compiles the version of paste in the working tree.
8. Access your fake domain over https.

# Ideas to simplify this

- Some sort of binary or script that takes care of starting, stopping, and restarting the webserver would be ideal.
- TLS requirement is great, but it hurts local dev. How can we streamline this?
  - For example, my laptop has `mkcert` installed, the CA for that installed in Firefox, and an entry in `/etc/hosts` set up to point `dev.paste.gg` to `127.0.0.1`. That's unreasonable to expect of someone that's not me.
  - Can we automate this somehow and just have some script output "Access https://dev.paste.gg/" or something like that?

Feedback about the setup process, contribution process, and ideas to help make everything easier is appreciated!

**Comment by jkcclemens** [comment]
One idea I've just had is actually pointing `dev.paste.gg` to `127.0.0.1` over real DNS. That doesn't take care of setting up a cert, but it does provide a way for people to have a set domain to test with, and then we don't have to muck with hosts files or DNS servers or anything.

Getting a browser to trust a cert is another story. paste assumes that you're connecting over TLS in a lot of places (citation needed - I remember needing to stop accepting non-TLS connections for some features), so I'm not sure if we can just allow plain HTTP connections.

**Comment by jkcclemens** [comment]
@bendem brought up using self-signed certificates for paste, which devs can just accept. We would need to put a script that runs the command below somewhere so that each person who starts paste generates their own cert.

`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365`

Perhaps this could just go in the script that starts paste and sets up the config files with a check to see if cert has already been generated (and if it has expired).

**Comment by jkcclemens** [comment]
`paste.sh` has been added to help remedy this, but it hasn't been documented in the readme. It makes the process two steps: `./paste.sh start` and then accessing `https://localhost` and accepting the self-signed cert. Then development can begin!

Is there any other part of contributing that's difficult besides the dev environment?

**Comment by jkcclemens** [comment]
I think it's much easier now, and no one has raised any issues. Re-open or make a new issue if there are any other hang-ups on contribution.

**Comment by lol768** [comment]
i think this is a good idea and once it works it will probably be the most painless project to set-up locally I've seen.

Thoughts:

* I preferred the script in the root, since it was obvious it was there. Dedicated directory is fine, but the first mention of this in the README is _right at the bottom_  after scary instructions for deploying to prod (which is obviously more involved than running the development server). I think I'd re-order where these appear in the README.
* Script doesn't work if you run it from within the `scripts/` directory. Should fail fast and tell the user how to run it if there's no desire to automatically work out paths at start-up time.
* Could do with some documentation as to the requirement to not have anything already listening on port 80 on the host.
* Could do with some documentation to make it clear that `Starting paste-dev_nginx_1 ... done` being logged to the console _does not imply_ that the server will be running and there is an additional 5 minutes or so of time to wait whilst crates are downloaded and compiled before the server will start.
* What are the system requirements? I already had docker and docker-compose installed, but presumably folks will need to install these.

This happened during start-up a bunch of times:

```
sidekiq_1   | 2019-10-13T13:34:38.623Z pid=6 tid=grjsbmq8q INFO: Booting Sidekiq 6.0.1 with redis options {:id=>"Sidekiq-server-PID-6", :url=>""}
sidekiq_1   | invalid uri scheme ''
sidekiq_1   | /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:438:in `_parse_options'
sidekiq_1   | /usr/local/bundle/gems/redis-4.1.3/lib/redis/client.rb:83:in `initialize'
sidekiq_1   | /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:45:in `new'
sidekiq_1   | /usr/local/bundle/gems/redis-4.1.3/lib/redis.rb:45:in `initialize'
sidekiq_1   | /usr/local/bundle/gems/sidekiq-6.0.1/lib/sidekiq/redis_connection.rb:57:in `new'
sidekiq_1   | /usr/local/bundle/gems/sidekiq-6.0.1/lib/sidekiq/redis_connection.rb:57:in `build_client'
sidekiq_1   | /usr/local/bundle/gems/sidekiq-6.0.1/lib/sidekiq/redis_connection.rb:36:in `block in create'
sidekiq_1   | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:171:in `try_create'
sidekiq_1   | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:83:in `block (2 levels) in pop'
sidekiq_1   | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:79:in `loop'
sidekiq_1   | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:79:in `block in pop'
sidekiq_1   | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:78:in `synchronize'
sidekiq_1   | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:78:in `pop'
sidekiq_1   | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:93:in `checkout'
sidekiq_1   | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:62:in `block in with'
sidekiq_1   | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
sidekiq_1   | /usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
sidekiq_1   | /usr/local/bundle/gems/sidekiq-6.0.1/lib/sidekiq.rb:94:in `redis'
sidekiq_1   | /usr/local/bundle/gems/sidekiq-6.0.1/lib/sidekiq.rb:112:in `redis_info'
sidekiq_1   | /usr/local/bundle/gems/sidekiq-6.0.1/lib/sidekiq/cli.rb:58:in `run'
sidekiq_1   | /usr/local/bundle/gems/sidekiq-6.0.1/bin/sidekiq:12:in `<top (required)>'
sidekiq_1   | /usr/local/bundle/bin/sidekiq:23:in `load'
sidekiq_1   | /usr/local/bundle/bin/sidekiq:23:in `<main>'
paste-dev_sidekiq_1 exited with code 1
```

Unsure what sidekiq does/what it's for.

I'm told `Rocket has launched from https://0.0.0.0:8000` and the Rust app seems to be running, but when I try to access `https://localhost`, Firefox doesn't connect. Have tried `127.0.0.1` and `::1`. I see `paste-dev_nginx_1 exited with code 1`, so wondering if nginx has fallen over.

Indeed, if I check the container logs I see the below:

<details>
<pre>
2019/10/13 13:32:03 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:32:04 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:32:05 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:32:06 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:32:08 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:32:10 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:32:15 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:32:22 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:32:35 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:33:01 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:33:54 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:34:55 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:35:56 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
2019/10/13 13:36:56 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
</pre>
</details>

**Comment by lol768** [comment]
If you agree the docs changes are worthwhile, I'm happy to open some PRs, of course!

**Comment by jkcclemens** [comment]
> I preferred the script in the root, since it was obvious it was there. Dedicated directory is fine, but the first mention of this in the README is right at the bottom after scary instructions for deploying to prod (which is obviously more involved than running the development server). I think I'd re-order where these appear in the README.

You can put the local dev env instructions above deploying for prod, if you prefer.

> Script doesn't work if you run it from within the scripts/ directory. Should fail fast and tell the user how to run it if there's no desire to automatically work out paths at start-up time.

The script and the docs for it do mention that you must run it from the repo root. Could add a check for `.git` in the same dir and fail with an explanation.

> Could do with some documentation as to the requirement to not have anything already listening on port 80 on the host.

Yup.

> Could do with some documentation to make it clear that Starting paste-dev_nginx_1 ... done being logged to the console does not imply that the server will be running and there is an additional 5 minutes or so of time to wait whilst crates are downloaded and compiled before the server will start.

Documentation does say it needs to compile, which can take time.

> What are the system requirements? I already had docker and docker-compose installed, but presumably folks will need to install these.

The script will fail and tell you what you're missing, but you need `docker`, `docker-compose`, `openssl`, `sed`, `grep`, `groups`, `sudo` if you're not in the docker group.

I'm not sure why sidekiq was giving you that error. Generally it will error that it's missing dynamic libraries until compilation finishes. sidekiq is for emails/mass deletions, btw. What does your `sidekiq.sh` look like?

Yes, your nginx is failing to start because you didn't use `git lfs`, so the modules are failing to load. That does need to be documented.
