### ISSUE TITLE
Public and unlisted paste visibilities appear to be identical

### ISSUE THREAD

**Issue by xfix** [jkcclemens/paste#185]
**Is your feature request related to a problem? Please describe.**

I'm always overjoyed when "public" and "unlisted" paste visibilities appear to do the exact same thing.

**Describe the solution you'd like**

Remove visibility selection for guests.

**Describe alternatives you've considered**

Maybe change visibility names to say something about search engines, dunno? Unlisted pastes have `<meta name="robots" content="noindex, nofollow"/>` in the code, but that's not really visible to the user.

**Comment by jkcclemens** [comment]
Thanks for the issue!

> "public" and "unlisted" paste visibilities appear to do the exact same thing.

Public pastes are publicly available, shown in the API, and can be indexed by search engines. Unlisted pastes are not shown in the API, cannot be indexed, and can only be found by those with the URL. I'm sure you've surmised this.

I agree that it would be nice to have some extra clarification for the user about the difference between public and unlisted. On the other hand, this is extra low priority because the difference is literally in the name.

> Maybe change visibility names to say something about search engines, dunno?

Visibility names aren't going to change, but additional information can be added, probably in a help tooltip.

> Remove visibility selection for guests.

Why? There is a distinction between public and unlisted, and I don't see a reason to make every anonymous paste either public or unlisted. Do you have a good reason for this?

**Comment by xfix** [comment]
I sorta feel like users won't care to set a privacy level, and just leave the defaults - from my experience as a mod on Pokemon Showdown (IRC-like service), mods sometimes post stuff like PM logs on pastebin.com (because it's unfortunately the most popular service), leaving them as public. We do tell to not post stuff like that on pastebins, and yet people ignore. Oh well.

That said, I don't particularly care what you decide on - the difference is so small that the users probably won't care and just go with the default. Just please the default never be "displayed on the home page so that a search engine would easily index it".

**Comment by jkcclemens** [comment]
The default already *is* unlisted for that purpose. There could be a config option to change the default or not allow public anonymous pastes (or both). I'm not seeing the issue in what you're saying, though.

The defaults are already set to reasonable defaults. ?

**Comment by xfix** [comment]
Yes. In short, the issue is that there are two very similar options that the typical user won't be able to tell a difference about (even if you put a help text) - "an user may think that say 'public means it can be shared with other people'". That said, in this case it's mostly harmless, as both options are pretty much identical.

**Comment by jkcclemens** [comment]
The difference is important, though. As a comparison with Gist, public is a normal gist and unlisted is a secret gist. They're two different types because the difference really isn't that small.

This issue has now pointed to users blindly accepting defaults and users changing the visibility from the default.

Are you just looking to have unlisted/public changed to a different word because the average user won't understand the difference?

Alternatively, if you're hosting your own, solving your issue could be done by not allowing public pastes from anonymous (or even authenticated) users as an option in the config.

**Comment by lol768** [comment]
I think the messaging could be clearer. I don't know what's different about gists but the public gists "feel" different. You'd see them on profile pages etc

Maybe we can explain in a popover of something when they pick

**Comment by lol768** [comment]
Or hell, even just underneath.

I'd also suggest different icons - currently we have the globe for both.

**Comment by jkcclemens** [comment]
Yes, I fully agree it could be clearer what the difference is. Like I mentioned, we could add a little question mark popover.

> I'd also suggest different icons - currently we have the globe for both.

I'm not sure how to do that, really. Not sure if Bulma can without JS.

**Comment by jkcclemens** [comment]
See [this video][video] for an implementation I think would help. With JS off, the icons don't change (this isn't possible via CSS without parent styling), but the icon stays as the default unlisted icon.

[video]: https://streamable.com/djc15
