### ISSUE TITLE
Preserve field values on error

### ISSUE THREAD

**Issue by bendem** [jkcclemens/paste#35]
When submitting a paste without files, the title and description fields are reset. Values should be kept instead.

**Comment by jkcclemens** [comment]
Is there a way to do this that isn't "give the values back in the template context?"

**Comment by bendem** [comment]
probably using some javascript trickery to save values before submit, but otherwise, setting the input values in the template if they were included in the request's post data is the way to do it

**Comment by jkcclemens** [comment]
Yeah, that's what I didn't want to do. Oh well, that'll happen eventually, then.

**Comment by lol768** [comment]
ASP.NET's templating language has a concept of tag herlpers, so you can register code which then transparently works on e.g. `<input>` elements which have an `asp-for` attribute pointing at a model item - and fills in a `value` attribute if there are previously submitted values available.

Maybe you vould emulate something like this using Tera macros?

**Comment by jkcclemens** [comment]
Note that the currently-implemented solution does not restore file names/contents when creating a new paste or editing an existing paste.

The only time in which uploading a file because of name/content should fail is when they're too long or empty. Ideally, the valid ones would be restored, but it's a bit of a PITA to implement, since multiple files is handled via JS.
